#!/bin/zsh

function aptInstall {
  if [[ -z "$1" ]]; then
    echo "Invalid argument missing component name"
    return 1
  fi

  # Guard clause to not install more than once
  if ! which -s "$1"; then
    echo "$1 is installed"
    return 0;
  fi

  echo "Installing $1 from apt-get"
  sudo apt-get update
  sudo apt-get install "$1" -y
}

# Setup Config files for managing dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
config config --local status.showUntrackedFiles no

if [ "$#" -ne 2 ]; then
  echo "Please call this script with the desired git user.name and user.email:"
  echo "./setup \"username\" \"user.email\""
  exit 1
fi

[[ "$1" == $(config config user.name) ]] || config config user.name "$1"
[[ "$2" == $(config config user.email) ]] || config config user.email "$2"

if [ ! -d ~/.oh-my-zsh ]; then
  sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
  echo "Restart the script to complete the setup"
  exit 0
fi

if ! grep -q "alias config=" $HOME/.zshrc; then
  echo "alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'" >> $HOME/.zshrc
fi

if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  sed -i 's/^plugins=(\(.*\))/plugins=(\1 zsh-autosuggestions)/' $HOME/.zshrc
fi

if ! which -s rustup; then
  echo "Installing Rust via Rustup"
  aptInstall build-essential
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  exit 0
fi

if ! which -s unzip; then
  echo "gah; unzip not found"
else
  echo "gah: unzip found"
fi

aptInstall unzip

if ! which -s xclip; then
  echo 'Installing xclip'
  sudo apt-get update
  sudo apt-get install xclip -y
fi

if ! which -s bob; then
  echo "Installing Bob and NeoVim"
  cargo install bob-nvim
fi

if ! which -s nvim; then
  echo "Installing NeoVim Stable"
  bob install stable
  bob use stable
  echo 'export PATH=$PATH:$HOME/.local/share/bob/nvim-bin' >> $HOME/.zshrc
  echo 'Restart the terminal or source .zshrc to access nvim'
fi

if ! which -s starship; then
  echo "Installing Starship Prompt 🚀"
  sudo apt-get update
  sudo apt-get install cmake
  cargo install starship --locked
  echo 'eval "$(starship init zsh)"' >> $HOME/.zshrc
fi

if ! which -s bat; then
  echo "Installing bat"
  cargo install bat --locked
  echo "alias cat=bat -h" >> $HOME/.zshrc
fi

 if ! which -s rg; then
  echo "Installing ripgrep"
  cargo install ripgrep --locked
fi

if ! which -s eza; then
  echo "Installing Eza"
  cargo install eza --locked
  echo "alias ls=eza -h" >> $HOME/.zshrc
fi
  
if ! which -s tldr; then
  echo "Installing TealDeer"
  cargo install tealdeer --locked
fi

if ! which -s porsmo; then
  echo "Installing Porsmo"
  aptInstall libasound2-dev
  aptInstall librust-alsa-sys-dev
  cargo install porsmo 
fi

#if ! which -s gitui; then
#  echo "Installing GitUI"
#  cargo install gitui
#fi

if ! which -s mise; then
  echo "Installing mise"
  sudo apt-get update
  sudo apt-get install libssl-dev
  cargo install mise
  echo 'eval "$(mise activate zsh)"' >> "${ZDOTDIR-$HOME}/.zshrc"
fi


