return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  lazy = false,
  build = ':TSUpdate',
  opts = {
    -- indent = { enable = true },
  },
  init = function()
    local ts = require('nvim-treesitter')

    ts.install {
      'angular',
      'bicep',
      'bash',
      'c_sharp',
      'comment',
      'css',
      'dockerfile',
      'editorconfig',
      'fish',
      'fsharp',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'goctl',
      'gomod',
      'gosum',
      'gotmpl',
      'html',
      'javascript',
      'json',
      'json5',
      'latex',
      'lua',
      'luadoc',
      'make',
      'markdown',
      'markdown_inline',
      'mermaid',
      'powershell',
      'python',
      'rust',
      'regex',
      'scss',
      'svelte',
      'tsx',
      'typescript',
      'typst',
      'vue',
      'xml',
      'yaml',
    }

  end
}
