return {
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  lazy = false,
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'angular',
      'bash',
      'c_sharp',
      'css',
      'dockerfile',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'html',
      'javascript',
      'json',
      'json5',
      'lua',
      'luadoc',
      'lua_patterns',
      'markdown',
      'markdown_inline',
      'mermaid',
      'python',
      'rust',
      'typescript',
      'vimdoc',
      'vue',
      'xml',
      'yaml',
    },
    sync_install = false,
    auto_install = true,
    ignore_installed = {},
    highlight = { enable = true, },
  }
}
